name: CI - Main Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions: write-all

jobs:
  test-and-evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
      
    - name: Setup CML
      uses: iterative/setup-cml@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure DVC Remote (GCS)
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > gcs-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=gcs-key.json
        dvc remote modify storage credentialpath gcs-key.json
        
    - name: Pull data and model from DVC
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=gcs-key.json
        dvc pull
        
    - name: Run all tests
      run: |
        pytest tests/ -v --tb=short
        
    - name: Evaluate model
      run: |
        python src/evaluate.py
        
    - name: Generate CML Report with Comparison
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "# ML Pipeline Report - Main Branch" > report.md
        echo "" >> report.md
        echo "## Test Results" >> report.md
        echo "✅ All tests passed successfully" >> report.md
        echo "" >> report.md
        echo "## Model Performance Metrics" >> report.md
        cat results/metrics.txt >> report.md
        echo "" >> report.md
        echo "## Confusion Matrix Visualization" >> report.md
        cml publish results/confusion_matrix.png --md >> report.md
        cml comment create report.md
